from __future__ import annotations

from typing import Any


def build_forecast_source_fields(engine_name: str, model_info: dict[str, Any]) -> dict[str, Any]:
    artifact_available = bool(model_info.get("is_loaded"))
    artifact_status = "available" if artifact_available else "unavailable"
    return {
        "active_engine_name": engine_name,
        "model_artifact_status": artifact_status,
        "model_artifact_available": artifact_available,
        "forecast_source_label": f"Generated by: {engine_name}",
    }

