from __future__ import annotations

from typing import Any, Iterable


def build_forecast_source_fields(engine_name: str, model_info: dict[str, Any]) -> dict[str, Any]:
    artifact_available = bool(model_info.get("artifact_validated_for_inference", model_info.get("is_loaded")))
    artifact_status = "available" if artifact_available else "unavailable"
    return {
        "active_engine_name": engine_name,
        "model_artifact_status": artifact_status,
        "model_artifact_available": artifact_available,
        "forecast_source_label": f"Generated by: {engine_name}",
    }


def _value(obj: Any, attr: str, default: Any = None) -> Any:
    if isinstance(obj, dict):
        return obj.get(attr, default)
    return getattr(obj, attr, default)


def build_priority_fields(financial_exposure: dict[str, float], replenishment: Iterable[Any]) -> dict[str, Any]:
    exposure = float(financial_exposure.get("stockout_exposure_rm", 0.0) or 0.0) + float(
        financial_exposure.get("waste_exposure_rm", 0.0) or 0.0
    )
    shortage = sum(float(_value(line, "shortage_qty", 0.0) or 0.0) for line in replenishment)
    score = round(exposure + shortage * 10.0, 2)
    if exposure > 0 and shortage > 0:
        reason = "highest combined financial exposure and ingredient shortage"
    elif exposure > 0:
        reason = "highest financial exposure"
    elif shortage > 0:
        reason = "ingredient shortage impact"
    else:
        reason = "backend optimizer priority"
    return {"priority_score": score, "priority_reason": reason}


def build_forecast_line_payloads(forecast_lines: Iterable[Any], outlets_map: dict[int, str], skus_map: dict[int, str]) -> list[dict[str, Any]]:
    return [
        {
            "outlet_id": line.outlet_id,
            "outlet_name": outlets_map.get(line.outlet_id, ""),
            "sku_id": line.sku_id,
            "sku_name": skus_map.get(line.sku_id, ""),
            "morning": round(line.morning, 1),
            "midday": round(line.midday, 1),
            "evening": round(line.evening, 1),
            "total": round(line.total, 1),
            "reason_tags": (line.rationale_json or {}).get("reason_tags", []),
        }
        for line in forecast_lines
    ]


def build_prep_line_payloads(prep_lines: Iterable[Any]) -> list[dict[str, Any]]:
    return [
        {
            "id": line.id,
            "outlet_id": line.outlet_id,
            "sku_id": line.sku_id,
            "daypart": line.daypart,
            "recommended_units": line.recommended_units,
            "edited_units": line.edited_units,
            "current_stock": line.current_stock,
            "status": line.status,
        }
        for line in prep_lines
    ]


def build_replenishment_line_payloads(replenishment_lines: Iterable[Any]) -> list[dict[str, Any]]:
    return [
        {
            "ingredient_id": line.ingredient_id,
            "ingredient_name": line.ingredient.name if line.ingredient else "",
            "need_qty": round(line.need_qty, 2),
            "stock_on_hand": round(line.stock_on_hand, 2),
            "reorder_qty": round(line.reorder_qty, 2),
            "unit": line.ingredient.unit if line.ingredient else "units",
            "urgency": line.urgency,
            "driving_skus": line.driving_skus or [],
        }
        for line in replenishment_lines
    ]


def build_full_plan_summary(
    *,
    total_predicted_sales: float,
    waste_risk_score: int,
    stockout_risk_score: int,
    legacy_top_actions: list[str],
    at_risk_outlets: list[str],
    prep_lines: Iterable[Any],
    action_candidates: Iterable[Any],
    replenishment_lines: Iterable[Any],
) -> dict[str, Any]:
    prep_line_list = list(prep_lines)
    action_list = list(action_candidates)
    replenishment_list = list(replenishment_lines)
    return {
        "scope": "full_plan",
        "total_predicted_sales": round(total_predicted_sales, 0),
        "waste_risk_score": waste_risk_score,
        "stockout_risk_score": stockout_risk_score,
        "top_actions": legacy_top_actions,
        "at_risk_outlets": at_risk_outlets[:5],
        "total_recommended_prep_units": int(
            sum((_value(line, "edited_units") if _value(line, "edited_units") is not None else _value(line, "recommended_units", 0)) for line in prep_line_list)
        ),
        "total_stockout_exposure_rm": round(
            sum(float(_value(_value(action, "financial_exposure", {}), "stockout_exposure_rm", 0.0) or 0.0) for action in action_list),
            2,
        ),
        "total_waste_exposure_rm": round(
            sum(float(_value(_value(action, "financial_exposure", {}), "waste_exposure_rm", 0.0) or 0.0) for action in action_list),
            2,
        ),
        "ingredient_shortage_count": sum(1 for line in replenishment_list if float(_value(line, "reorder_qty", 0.0) or 0.0) > 0),
        "pending_action_count": sum(1 for line in prep_line_list if _value(line, "status") != "accepted"),
    }
