import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/components/i18n/LanguageProvider";

interface Props {
  open: boolean;
  onClose: () => void;
  modelVersion: string;
  modelStatus: string;
  engineName: string;
  activeEngineName: string;
  dataSource: "backend";
  modelArtifactStatus: string;
  modelArtifactAvailable: boolean;
  forecastSourceLabel: string;
  validationWindow: string;
  metrics: {
    wape: number;
    bias: number;
    p10_p90_coverage: number;
    estimated_mismatch_cost_delta_pct: number | null;
  };
}

export default function ModelEvidenceDrawer({
  open,
  onClose,
  modelVersion,
  modelStatus,
  engineName,
  activeEngineName,
  dataSource,
  modelArtifactStatus,
  modelArtifactAvailable,
  forecastSourceLabel,
  validationWindow,
  metrics,
}: Props) {
  const { t } = useLanguage();
  const dataSourceLabel = dataSource === "backend" ? t("planning.source.backend", "Backend") : dataSource;
  const modelStatusLabel = modelStatus === "available" ? t("planning.available", "available") : modelStatus;
  const artifactStatusLabel = modelArtifactStatus === "available"
    ? t("planning.available", "available")
    : modelArtifactStatus === "missing"
      ? t("planning.missing", "missing")
      : modelArtifactStatus;
  if (!open) {
    return null;
  }

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/30">
      <div className="flex h-full w-full max-w-md flex-col bg-white shadow-xl">
        <div className="flex items-center justify-between border-b px-5 py-4">
          <div>
            <h3 className="text-sm font-semibold text-neutral-900">{t("planning.modelEvidence.title", "Model evidence")}</h3>
            <p className="text-xs text-neutral-500">{t("planning.validation", "Validation")}: {validationWindow}</p>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose}>
            {t("common.close", "Close")}
          </Button>
        </div>
        <div className="flex-1 space-y-4 overflow-auto px-5 py-4">
          <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-3">
            <p className="text-xs uppercase tracking-wide text-neutral-500">{t("planning.status", "Status")}</p>
            <p className="text-sm font-semibold text-neutral-900">{modelStatusLabel}</p>
            <p className="text-xs text-neutral-500">{t("planning.source", "Source")}: {dataSourceLabel}</p>
            <p className="text-xs text-neutral-500">{t("planning.activeEngine", "Active engine")}: {activeEngineName}</p>
            <p className="text-xs text-neutral-500">{t("planning.engine", "Engine")}: {engineName}</p>
            <p className="text-xs text-neutral-500">
              {t("planning.forecastSourceLabel", "Generated by: {{engine}}", {
                engine: forecastSourceLabel.includes(":")
                  ? forecastSourceLabel.split(":").slice(1).join(":").trim() || engineName
                  : engineName,
              })}
            </p>
            <p className="text-xs text-neutral-500">
              {t("planning.artifact", "Artifact")}: {artifactStatusLabel} (
              {modelArtifactAvailable
                ? t("planning.available", "available")
                : t("planning.managerNote.unavailable", "unavailable")}
              )
            </p>
            <p className="text-xs text-neutral-500">{t("planning.version", "Version")}: {modelVersion}</p>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2">
              <span className="text-xs text-neutral-500">{t("planning.wape", "WAPE")}</span>
              <Badge variant="info">{(metrics.wape * 100).toFixed(1)}%</Badge>
            </div>
            <div className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2">
              <span className="text-xs text-neutral-500">{t("planning.bias", "Bias")}</span>
              <Badge variant="outline">{(metrics.bias * 100).toFixed(1)}%</Badge>
            </div>
            <div className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2">
              <span className="text-xs text-neutral-500">{t("planning.p10p90Coverage", "p10-p90 coverage")}</span>
              <Badge variant="low">{(metrics.p10_p90_coverage * 100).toFixed(0)}%</Badge>
            </div>
            <div className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2">
              <span className="text-xs text-neutral-500">{t("planning.mismatchDelta", "Mismatch cost delta")}</span>
              <Badge variant={metrics.estimated_mismatch_cost_delta_pct == null ? "outline" : "success"}>
                {metrics.estimated_mismatch_cost_delta_pct == null
                  ? t("common.unavailable", "Unavailable")
                  : `${(metrics.estimated_mismatch_cost_delta_pct * 100).toFixed(0)}%`}
              </Badge>
            </div>
          </div>
          <div className="rounded-lg border border-neutral-200 bg-amber-50 p-3 text-xs text-amber-900">
            {t(
              "planning.modelEvidence.note",
              "Live recommendations use the LightGBM backend engine and trained validation artifacts shown above."
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
